name: PHPUnit

on: [ push, pull_request ]

env:
  SWOOLE_VERSION: '5.0.0'
  SWOW_VERSION: 'develop'

jobs:
  ci:
    name: Test PHP ${{ matrix.php-version }} on ${{ matrix.engine }}
    runs-on: "${{ matrix.os }}"
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        php-version: [ '8.0', '8.1' ]
        engine: [ 'none', 'swoole', 'swow' ]
      max-parallel: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: phpize
          ini-values: opcache.enable_cli=0
          coverage: none
      - name: Setup Packages
        run: composer update -o --no-scripts
      - name: Run Test Cases
        run: |
          composer analyse
          composer test